name: 'Scan Sonar'
description: 'Report scan code app in sonar'

inputs:
  organization:
    description: 'organization Claro video'
    required: false
    default: ''
  projectKey:
    description: 'Name projectKey Sonar'
    required: true
  sonarToken:
    description: 'Token para Sonar'
    required: true


runs:
  using: 'composite'
  steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
       GITHUB_TOKEN: ${{ github.token }}
       SONAR_TOKEN: ${{ inputs.sonarToken }}
      with:
        args: >
            -Dsonar.organization=${{ inputs.organization }}
            -Dsonar.projectKey=${{ inputs.projectKey}}
            -Dsonar.go.coverage.reportPaths=coverage.out
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master      
      #timeout-minutes: '5'
      env:
        SONAR_TOKEN: ${{ inputs.sonarToken }}
        # SONAR_HOST_URL: https://sonarcloud.io # Opcional para SonarCloud

      # Tarea opcional: Imprime el estado en el log de GitHub Actions
    - name: "Display SonarCloud Status"
      shell: bash
      run: |
        echo "El estado del Quality Gate es ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"           
